[package]
name = "every-day"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
gloo-storage = "0.3.0"
yew = { version = "0.21", features = ["csr"] }
